package vx.seasons.season.biome

/**
 * Data structures matching the JSON schema generated by the AI.
 */
data class BiomeColorPalette(
    val grassColor: String,
    val foliageColor: String,
    val waterColor: String,
    val waterFogColor: String,
    val skyColor: String,
    val fogColor: String
)

data class SeasonalVariants(
    val normal: BiomeColorPalette,
    val alternate: BiomeColorPalette
)

data class GeneratedBiomeContainer(
    val spring: SeasonalVariants,
    val summer: SeasonalVariants,
    val autumn: SeasonalVariants,
    val winter: SeasonalVariants
)